### ISSUE TITLE
Configuration warning: unrecognized property 'warmup'

### ISSUE THREAD

**Issue by sEnergy** [juanjoDiaz/serverless-plugin-warmup#237]
serverless.yml
```
  ep_install:
    handler: ep_install.handler
    timeout: 10 # sometimes the Oauth call via SlackAPI takes long
    events:
      - http:
          path: install
          method: get
          integration: lambda-proxy
    warmup:
      enabled: true
```

On `sls deploy`, I get this warning:
```
C:\Users\Marcel\Desktop\weekaz\src>sls deploy
Serverless: Configuration warning:
Serverless:   at 'functions.ep_install': unrecognized property 'warmup'
```

The warmup works, but this warning makes me nervous. What can it be done about it?
