### ISSUE TITLE
No plugin available in the package you provided error

### ISSUE THREAD

**Issue by jbprat** [juanjoDiaz/serverless-plugin-warmup#240]
Hello,

I'm testing your package by following these steps: https://www.serverless.com/blog/keep-your-lambdas-warm. I tried to go through the configuration steps but I have this error while trying to deploy: `No warmUpPlugin.zip file found in the package path you provided`. While I can see the zip at the root of the .serverless folder, but not in the serverless zip.

Here my serverless version:
```
Framework Core: 2.16.1
Plugin: 4.3.0
SDK: 2.3.2
Components: 3.4.3
```

Here is the version of serverless-plugin-warmup:  `^4.9.0`

Here is my serverless.yml:
```
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-warmup
 [...]
functions:
  getUser:
    handler: users/handler.getUser
    events:
      - http:
          path: user
          method: get
          cors: true
    warmup: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'lambda:InvokeFunction'
        Resource: '*'
```

Is there anything I'm missing?

**Comment by huatzhi** [comment]
Try excluding files that's unnecessary.

```yml
package:
  individually: true
  exclude:
    - tests/**
    - lib/**
    - share/**
    - man/**
    - bin/**
    - serverless/**
```

At least this is how I fix it. No idea why it fix it tho.

**Comment by juanjoDiaz** [comment]
Can you give me a complete yaml file so I can reproduce the issue?

@huatzhi do you set that at the function level or at the service level?

**Comment by jbprat** [comment]
Hi @juanjoDiaz,

Packaging individually on the service level fixed the issue for me, so thank you. I wasn't successfull at creating the package at the function level, but I'm still a beginner to serverless.

Here is my cleaned serverless.yml for you:
```
service: zoum-zoum-serverless

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-warmup

package:
  individually: true
  exclude:
    - tests/**
    - lib/**
    - share/**
    - man/**
    - bin/**
    - serverless/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  profile: ...
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ...
    subnetIds:
      - ...
      - ...

functions:
  getUser:
    handler: users/handler.getUser
    events:
      - http:
          path: user
          method: get
          cors: true
    warmup: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'lambda:InvokeFunction'
        Resource: '*'

```
