### ISSUE TITLE
Lambda with alias does not get triggered as intended

### ISSUE THREAD

**Issue by ramgrandhi** [juanjoDiaz/serverless-plugin-warmup#241]
Hello -
This is a nifty plugin, thanks for that!

### What
I have recently configured this plugin on my lambda which uses an alias to point at the latest deployed version.
I would like to have the warmup plugin keep the lambda function version warm which was configured behind that alias (at any given time). 

### How it's implemented?
1. My lambda is deployed and latest deployment is pointing to an alias **:live**

2. Here is the warmup settings in `serverless.yml`

```
custom:
  warmup:
    events:
      - schedule: cron(0/5 8-18 ? * MON-FRI *)
    name: lambda-warmer
    concurrency: 1
    prewarm: true
    vpc: false

functions:
  <function-name>:
    warmup:
      name: <function's logical name>:live
      enabled: true
```

### Behaviour Observed
* Warmup plugin is doing its job finely, so I can see a dedicated CloudWatch log group is updating every 5 mins with the warmup call logs. 
* However, when the real client application invokes the same lambda (with alias **:live**), AWS does not want to reuse the warmed-up container of that lambda instead it is creating a new lambda container (new CloudWatch log group) hindering the very basic premise of pre-warming it.

Please suggest.

Cheers,
ram

**Comment by juanjoDiaz** [comment]
The name prop is only usable in the service level and it's the name given to the actual warmer function, not the name of the function to warm up.

The solution, I just realized, is not documented. It uses the 
You can pass the alias to warmup using the environment variable `SERVERLESS_ALIAS`.
The warmer will use that alias for all the functions to warm up. If you want different aliases for different functions, you need to wait for version 5 which supports multiple warmers.

```yaml
custom:
  warmup:
    events:
      - schedule: cron(0/5 8-18 ? * MON-FRI *)
    concurrency: 1
    prewarm: true
    vpc: false
    environment:
      SERVERLESS_ALIAS: live

<function-name>:
  warmup:
    enabled: true
```
