### ISSUE TITLE
Serverless warmup multiple function attachment 

### ISSUE THREAD

**Issue by bwaghmare** [juanjoDiaz/serverless-plugin-warmup#242]
How to attach multiple warmer functions for the same lambda.

I.e. Lambda Name - Test-Lambda

```yaml
Test-Lambda:
    warmup:
      enabled: true

warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: 'cron(0/5 10-11 ? * * *)'
      concurrency: 5
    outOfOfficeHoursWarmer:
      enabled: true
      events:
        schedule: 'cron(0/5 4-6 ? * * *)' 
      concurrency: 3
```
      
      
      
  I wanted to ping Test-Lambda as per officeHoursWarmer  and outOfOfficeHoursWarmer
