### ISSUE TITLE
Define the name of cloudwatch rule

### ISSUE THREAD

**Issue by gipsh** [juanjoDiaz/serverless-plugin-warmup#243]
Hi, 

Is it possible to define the name of the rule that is created on cloudwatch the 
same way i can define the name of the lambda ?

The current patern is truncated and difficult to relate to my lambdas. 

Thanks!

**Comment by juanjoDiaz** [comment]
Yes, you can.

The `events` option is a standard serverless event.

So you should be able to do:
```yaml
events:
  - schedule:
      name: your-scheduled-rate-event-name
      description: 'your scheduled rate event description'
      rate: rate(5 minutes)
```
as stated in the docs (https://www.serverless.com/framework/docs/providers/aws/events/schedule/)
