### ISSUE TITLE
Error Upgrading to 5.0.0

### ISSUE THREAD

**Issue by paulalex** [juanjoDiaz/serverless-plugin-warmup#244]
Hi,

Trying to upgrade the plugin to 5.0.0 and I am getting the following error in my pipeline:

```

Type Error ---------------------------------------------
--
1077 |  
1078 | TypeError: serverless.configSchemaHandler.defineFunctionProperties is not a function

node_modules/serverless-plugin-warmup/src/schema.js:133:34
```

This is more a request for information\assistance really but I cannot work out what is causing the issue based on the error message, is this something you can assist with?

# Environment in build agent

```
Your Environment Information ---------------------------
--
1133 | Operating System:          linux
1134 | Node Version:              12.20.0
1135 | Framework Version:         1.83.2
1136 | Plugin Version:            3.8.4
1137 | SDK Version:               2.3.2
1138 | Components Version:        2.34.9
```

# Warm up config 

```
warmup:
    folderName: ".warmup"
    cleanFolder: false
    memorySize: 256
    name: "${self:custom.apiPrefix}-keep-alive"
    role:  WarmUpRole
    events:
      - schedule: "cron(0/5 8-17 ? * MON-FRI *)"
    vpc: false
    package:
      individually: true
    concurrency: 2
    timeout: 20
    prewarm: true # Run WarmUp immediately after a deployment
    tags:
      Project: My-Project
```

**Comment by juanjoDiaz** [comment]
Hi @paulalex ,

The `defineFunctionProperties ` method was added in [v2.10.0](https://github.com/serverless/serverless/releases/tag/v2.10.0).
You need to update your version of the framework or stick to v4.X of this plugin.

I'll update the readme to show that.
It's hard to keep track of compatibility with the serverless framework since they move fast and don't have a simple browsable and complete changelog. 😅

**Comment by paulalex** [comment]
@juanjoDiaz Thanks for the reply! Ok, that makes sense, I have a ticket to upgrade to `v2` but when I initially started to look at this there were so many errors I had to park it.

I just looked on the main plugin readme where it suggested "**_Recommended v1.33.x or higher_**".

I have cancelled the dependabot upgrade for now and rolled back but will need to set aside some more time for the serverless upgrade I think.

Cheers!

**Comment by juanjoDiaz** [comment]
Hi @paulalex,
I've released v5.1.0 which brings backward compatibility for older versions of the framework.
Just in case you want to give it a go 🙂

**Comment by paulalex** [comment]
@juanjoDiaz - Thanks a lot, just created a ticket to do this upgrade across our projects next sprint.

**Comment by juanjoDiaz** [comment]
Yes. The configuration has changed slightly.
Please read how to migrate in the readme.

v5 supports multiple warmers so you need to do something like:

```yaml
warmup:
  default:
    folderName: ".warmup"
    cleanFolder: false
    memorySize: 256
    name: "${self:custom.apiPrefix}-keep-alive"
    role:  WarmUpRole
    events:
      - schedule: "cron(0/5 8-17 ? * MON-FRI *)"
    vpc: false
    package:
      individually: true
    concurrency: 2
    timeout: 20
    prewarm: true # Run WarmUp immediately after a deployment
    tags:
      Project: My-Project

functions:
  hello:
    # ...
    warmup:
      default:
        enabled: true
```
I've name d the warmer `default` but you can name it however you want.
