### ISSUE TITLE
Warmup occurs at 2 minutes, irrespective of given schedule

### ISSUE THREAD

**Issue by praneetrattan** [juanjoDiaz/serverless-plugin-warmup#247]
Hello,

I'm using the warmup plugin to avoid cold starts for some of my lambdas. In the config, I set my schedule as every 4 minutes, yet, the warmup lambdas are being called at every 2 minute. Please see the config below and the screenshot of warmups.

I am on v5.0.0 now, but I have seen this happen starting v4.9.x. I tried 5 minutes on schedule, yet the calls were being made every 2 mins.

```
get:
    handler: account.get
    warmup:
      default:
        enabled: true
        concurrency: 1
        prewarm: false
        events:
          - schedule: rate(4 minutes)
        timeout: 8
        tags:
          stack: account
          stage: staging
          warmer: 'yes'
    events:
      - http:
      ...
```

<img width="1516" alt="Screen Shot 2021-02-07 at 8 40 45 AM" src="https://user-images.githubusercontent.com/5843603/107148246-355ba300-6920-11eb-8f96-cc8547cd93f7.png">
