### ISSUE TITLE
Doesn't warmup when deploying just a function

### ISSUE THREAD

**Issue by iPherian** [juanjoDiaz/serverless-plugin-warmup#265]
## Issue

On a normal deploy, warming up is done:

```serverless deploy --stage dev```

```
Serverless: WarmUp: Prewarming up you functions using warmer "default".
Serverless: WarmUp: Warmer "default" successfully prewarmed your functions.
```

but when deploying just a function it isn't:

```serverless deploy --stage dev function -f mainFunc```

## Expected Behavior

when prewarm: true is set, deploying only functions causes warmup

## Details

Can run a GET to `https://AWS_GATEWAY_HOST/dev/main` after just deploying function and check logs to see if it had been warmed up.

serverless.yml:

```
service: issueWithWarmupPlugin

plugins:
  - serverless-plugin-warmup

provider:
  name: aws

functions:
  mainFunc:
    handler: src/index.mainFunc
    events:
      - http:
          path: main
          method: get

custom:
  warmup:
    default:
      enabled: true
      prewarm: true
```

example repo:
https://github.com/iPherian/serverless-warmup-plugin-bug
