### ISSUE TITLE
Tracing option do not work

### ISSUE THREAD

**Issue by lucasgiusti** [juanjoDiaz/serverless-plugin-warmup#274]
Hello,

The tracing option do not work with the source below:

in package.json
```
"dependencies": {
    "aws-sdk": "^2.901.0",
    "aws-xray-sdk-core": "^3.3.3",
    ...
   "devDependencies": {
    "serverless": "^2.40.0",
    "serverless-api-compression": "^1.0.1",
    "serverless-offline": "^7.0.0",
    "serverless-plugin-warmup": "^4.9.0",
    "serverless-prune-plugin": "^1.5.0"
  }
```

in serverless.yml
```
...
plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-prune-plugin
  - serverless-api-compression
...
custom:
warmup:
    enabled: true
    prewarm: true
    schedule: rate(5 minutes)
    timeout: 60
    concurrency: 5
    vpc: false
    tracing: true
```
 

in handler.js
```
const AWSXRay = require('aws-xray-sdk-core');

const segment = AWSXRay.getSegment();
 let subsegment = segment.addNewSubsegment('v1.0');
 /* code */
 subsegment.close();
```

When I enable tracing option on aws console, this code is work successfully.
And the warmup is work successfully too.

Can you help me?
