### ISSUE TITLE
V5 to v6 migration

### ISSUE THREAD

**Issue by Euclidean-Dev** [juanjoDiaz/serverless-plugin-warmup#286]
With v5, it wasn't necessary to define anything more than: 
 ```
warmup:
    default:
        enabled: true
```
Following upgrade to v6 this error was generated during deploy:
```
 Serverless Error ----------------------------------------
     No file matches include / exclude patterns
```
Attempting to resolve this by adding the below to the warmup > default declaration but serverless deploy hung (no error):
```
warmup:
    default:
        enabled: true
        package:
            individually: true
            patterns:
                - "../**"
```
I am guessing something is wrong with the above.  Ideally I think it would be great if v6 could still interpret the most simple v5 config.
