### ISSUE TITLE
Remove global lambdaLayer from warmup lambdas

### ISSUE THREAD

**Issue by swirkens** [juanjoDiaz/serverless-plugin-warmup#290]
Hi,
I have globally set lambda layer for all my lambdas. Is there any way to detach it from warmup lambda? Can't see this option in config.

serverless.yml
```
plugins:
  - serverless-webpack
  - serverless-latest-layer-version
  - serverless-plugin-warmup

provider:
  name: aws
...
  layers:
    - arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:layer:${self:custom.lambdaLayerName}:latest

functions:
  ...
```
