### ISSUE TITLE
Prewarm not using custom payload

### ISSUE THREAD

**Issue by dylan-hoefsloot** [juanjoDiaz/serverless-plugin-warmup#292]
I have something similiar to the following
```yml
warmup:
  default:
    prewarm: true
    enabled: true
    payload: 
      requestContext:
        requestId: "custom-request-id"
```
however on the `prewarm` request, or the first execution on deployment it seems to be sending the default payload with
```json
{ 
  "Event": { 
    "source": "serverless-plugin-warmup"
  }
}    
```
and any subsequent request works as expected by sending the custom payload
```json
{ 
  "Event": { 
    "requestContent": { 
      "requestId": "custom-request-id" 
    }
  }
}    
```
Is this expected behaviour?
