### ISSUE TITLE
Configuration warning from functions default

### ISSUE THREAD

**Issue by yusukegoto** [juanjoDiaz/serverless-plugin-warmup#295]
Since I updated serverless-plugin-warmup to v6.1.0, I've got the warning from schema validation when I run `sls package` (deploy is not tried).
Is this a bug of schema validation added at v6.1.0 or my config is wrong?

`Serverless: Configuration warning at 'functions.hello.warmup.default': unrecognized property 'enabled'`

My yml is like bellow.

```yml
custom:
  warmup:
    default:
      enabled: true
functions:
  hello:
    warmup:
      default:
        enabled: false
```

```
sls --version
Framework Core: 2.70.0 (local)
Plugin: 5.5.2
SDK: 4.3.0
Components: 3.18.1
```
