### ISSUE TITLE
Temporary folder "warmer" not removed on deploy 

### ISSUE THREAD

**Issue by gshawnr** [juanjoDiaz/serverless-plugin-warmup#298]
I encountered an error in version 6.2.0 that does not occur in 6.0.0.  When deploying, the temporary folder warmer (might be warmup) that is created for the deploy is not successfully removed (there is a comment in the deploy log "unable to remove temporary folder warmer/warmup .).  

Unfortunately, I did not save my fail logs.  Let me know if you need more information.

Config:
```yaml
plugins:
  - serverless-bundle
  - serverless-plugin-warmup

custom:
  warmup:
    warmer:
      enabled: true
      events:
        - schedule: cron(0/5 * * * ? *) #Cron Expression for every 5 minutes
      concurrency: 1

functionName:
    handler: handlers/functionName.function
    warmup:
      warmer:
        enabled: false
```
