### ISSUE TITLE
Getting Cannot access package artifact

### ISSUE THREAD

**Issue by qngdt** [juanjoDiaz/serverless-plugin-warmup#309]
My project is using [serverless-package-python-functions](https://github.com/ubaniabalogun/serverless-package-python-functions) for packaging Python functions. I'm getting this error when trying to package my functions with warmup plugin

```
Error:
Cannot access package artifact at "_build/{serviceName}-{stage}-warmup-plugin-default.zip" (for "warmUpPluginDefault"): ENOENT: no such file or directory, access '{serviceName}-{stage}-warmup-plugin-default.zip'
```
Here is my warmup config in the custom stage
```
warmup:
    default:
      enabled: false
      cleanFolder: false
      package:
        individually: True
        artifact: ${self:custom.pkgPyFuncs.buildDir}/{serviceName}-${opt:stage}-warmup-plugin-default.zip
``` 
And the config at the function I want to warmup
```
  warmup:
    default:
      enabled: true
```
From my knowledge it's looking for the zip file containing the content of `.warmup` folder. So I tried to add the `artifact` part in my warmup config, but the error still hasn't been resolved. Would love someone could help me on this

**Comment by juanjoDiaz** [comment]
You shouldn't really be using artifact since you are not providing your own zip.
Also indentation seems off.

This should do:
```yaml
warmup:
    default:
        enabled: false
        cleanFolder: false
```
