### ISSUE TITLE
Cannot find module 'handler' 

### ISSUE THREAD

**Issue by amtzm93** [juanjoDiaz/serverless-plugin-warmup#323]
Hello, I'm submitting the issue cause this error is throwing me in my serverless project after upgrading the `serverless-plugin-warmup` from version `4.9.0` to `8.0.0`.

```
ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'handler'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:951:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)",
        "    at async start (file:///var/runtime/index.mjs:1137:23)",
        "    at async file:///var/runtime/index.mjs:1143:1"
    ]
}
```
I know that `serverless-plugin-warmup` is working because it created the Warm Up Lambda with its configuration. But after that, all lambda functions can't be found, even if the lambda doesn't have the warm-up event, it can't be found.

Versions:
```
NodeJs: 16.x
Serverless: ~3.19.0
Serverless Plugin Warmup: ^8.0.0
Serverless Webpack:  5.9.1
Serverless Offline: 9.1.0
```
The functions configuration declared in the `serverless.yml` hasn´t been modified because previously the `serverless-plugin-warmup` every function was working and also, using `serverless-offline`, the project is working fine.

---
The `warmup` configuration in `serverless.yml`
```
warmup:
    default:
      cleanFolder: false
      name: custom-Name-Lambda
      events:
        - schedule: 'rate(5 minutes)'
      package:
        individually: false
      prewarm: true
      concurrency: 10 # Warm up 10 concurrent instances
```

**Comment by juanjoDiaz** [comment]
Hi @amtzm93,

Are you declaring `serverless-plugin-warmup` after `serverless-webpack`?

Can you create a sample project to reproduce the issue?
Otherwise there isn't much that I can't do to help....

**Comment by juanjoDiaz** [comment]
Closing since there was no response. Feel free to reopen if needed.

**Comment by reinvent-heucles** [comment]
Hey @juanjoDiaz I am having the same issue

NodeJs: 18.x
Serverless: 3.40.0
Serverless Plugin Warmup: 8.3.0

Here is my warmer config: 

```YAML
  warmup:
    default:
      enabled: true
      name: warmer-default
      folderName: ".warmup"            # Folder with generated warmup code
      events:
        - schedule: cron(0/5 * * * ? *)  # Every 5 minutes; adjust as needed
      payload:
        isWarmup: true                 # Use an object rather than a JSON string
      role: IamRoleLambdaExecution
      architecture: "arm64"
      prewarm: true
      package:
        individually: true
```

Can you give some pointer? 

Here is the lambda warmer

![Image](https://github.com/user-attachments/assets/150d0c7c-851b-4080-bb39-20802ba41783)

And the error
```

2025-02-01T07:09:07.040Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'handler'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}

```
