### ISSUE TITLE
warmup not working: is it because I use docker or I did something wrong?

### ISSUE THREAD

**Issue by alanwilter** [juanjoDiaz/serverless-plugin-warmup#328]
My `serverless.yml`:

```yml
...
frameworkVersion: "3"

provider:
  name: aws
  region: eu-west-2
  ecr:
    images:
      predgene_faf_1:
        path: ./
        file: Dockerfile_faf_1
...
functions:
  predictGene_faf_1:
    timeout: ${self:custom.timeout}
    image:
      name: predgene_faf_1
    environment:
      MODEL_PATH: "./model_weights_onnx/faf/17012021-173755-InceptionV3-100e-128bs-0.0001lr.onnx"
      BUCKET: ${self:custom.s3bucket.${sls:stage}.name}
    warmup:
      default:
        enabled:
          - dev
          - prod
...
custom:
  warmup:
    default:
      enabled: true
      events:
        - schedule: cron(0/5 1-23 ? * MON-SUN *)
      concurrency: 5
      verbose: true
      logRetentionInDays: 14
```

My setup:
```json
{
  "dependencies": {
    "serverless": "^3.21.0"
  },
  "devDependencies": {
    "serverless-plugin-warmup": "^7.3.0",
    "serverless-prune-plugin": "^2.0.1"
  }
}
```

In my handler:

```python
def handler(event, context, model=None):
    """Handler function for first model of eye2gene"""

    version = "0.3.0"

    if event.get("source") == "serverless-plugin-warmup":
        print("WarmUp - Lambda is warm!")
        return {}
...
```
And then, after a while without checking or using my lambda, I saw this with simple script I use to check:

```
>>> faf 1
        "State": "Inactive",
        "StateReason": "The function is currently idle.",
        "StateReasonCode": "Idle",
````

How can I know that warmup plugin is supposed to be doing its job? Where are the logs referred in `logRetentionInDays`?
