### ISSUE TITLE
warm up plugin webpack bundling  issue

### ISSUE THREAD

**Issue by Bhirahaspathi-Sairam** [juanjoDiaz/serverless-plugin-warmup#337]
I am using serverless warm up plugin in my project and it fails while bundling with webpack. I am not sure what the issue is.Below is the configs

```yaml
 warmup:
    default:
      cleanFolder: false
      memorySize: 256
      name: ${self:service}-${self:custom.stage}-warmer
   
      events:
        - schedule: 'cron(0/5 8-17 ? * MON-FRI *)'
      timeout: 20
      verbose: true
      logRetentionInDays: 14
      prewarm: true
      concurrency: 5
````

I have enabled warmup at function specific level.

Here is the output from jenkins
```sh
WarmUp: Creating warmer "default" to warm up 5 functions

Bundling with Webpack...

ERROR in ../../../.warmup/default/index.js 6:12-45

Module not found: Error: Can't resolve '@aws-sdk/client-lambda' in '/.warmup/default'
````

Can anyone tell me why its happening
