### ISSUE TITLE
How to disable warmers by default, and enable them only for specific lambdas?

### ISSUE THREAD

**Issue by arielbeckjit** [juanjoDiaz/serverless-plugin-warmup#343]
this is my warmup configurations:
```yaml
custom:
  warmup:
    workWeek:
      enabled: true
      events:
        - schedule: cron(*/10 5-19 ? * SUN-FRI *)
      concurrency: 3
      prewarm: false
      cleanFolder: false
      role: IamRoleLambdaExecution
    weekEnd:
      enabled: true
      events:
        - schedule: cron(*/30 5-13 ? * SAT *)
      concurrency: 1
      prewarm: false
      cleanFolder: false
      role: IamRoleLambdaExecution
```

the problem is, that every lambda i declare **automatically** gets this configuration, this is a problem as i thought by default it should not be enabled.

if i put this section on a specific lambda then it will not be warmed:
```yaml
    warmup:
      workWeek:
        enabled: false
      weekEnd:
        enabled: false
```

**Comment by juanjoDiaz** [comment]
You just do it the other way around.

In the general config, you configure your warmers as disabled:
```yaml
custom:
  warmup:
    workWeek:
      enabled: false
      events:
        - schedule: cron(*/10 5-19 ? * SUN-FRI *)
      concurrency: 3
      prewarm: false
      cleanFolder: false
      role: IamRoleLambdaExecution
    weekEnd:
      enabled: false
      events:
        - schedule: cron(*/30 5-13 ? * SAT *)
      concurrency: 1
      prewarm: false
      cleanFolder: false
      role: IamRoleLambdaExecution
```

and in the specific lambdas that you want to warm, you enable the warmer(s) that you want:

```yaml
    warmup:
      workWeek:
        enabled: true
      weekEnd:
        enabled: true
```
