### ISSUE TITLE
Tracing: warmer imports aws-xray-sdk but only aws-xray-sdk-core is installed → ReferenceError: AWSXRay is not defined in v8.3.0

### ISSUE THREAD

**Issue by deel77** [juanjoDiaz/serverless-plugin-warmup#360]
#### What happened

Enabling `tracing: true` (or `Active` / `PassThrough`) on a warmer function in **serverless-plugin-warmup v8.3.0** causes the generated `.warmup/<warmer>/index.mjs` to crash at runtime with:

```
ReferenceError: AWSXRay is not defined
    at file:///var/task/.warmup/default/index.mjs:11:22
```

#### Minimal reproducible example

```yaml
custom:
  warmup:
    default:
      enabled: true
      tracing: true          # ← triggers the bug
      events:
        - schedule: rate(5 minutes)
      concurrency: 1
```

Deployment succeeds, but the first scheduled invocation of the warmer fails with the stack trace above.

#### Why it breaks

`src/warmer.js` generates this code:

```js
import * as AWSXRay from 'aws-xray-sdk';
const lambdaClient = AWSXRay.captureAWSv3Client(uninstrumentedLambdaClient);
```

Immediately beforehand the plugin runs:

```bash
npm install --save aws-xray-sdk-core
```

*The full* `` package is never installed, so the ESM import resolves to an empty object and `AWSXRay` is `undefined`.\
AWS documentation shows that `captureAWSv3Client` lives in the full SDK, not `aws-xray-sdk-core`.

#### Expected behaviour

The warmer should succeed and traces should appear in X-Ray when `tracing` is enabled.

#### Environment

|                          | value                 |
| ------------------------ | --------------------- |
| serverless-plugin-warmup | 8.3.0                 |
| Serverless Framework     | 3.39.0                |
| Node.js runtime          | 20.x (lambda & local) |
| AWS region               | eu-central-1          |

#### Possible fixes

1. **Install the correct package**\
   Replace the npm command in `createWarmUpFunctionArtifact` with:
   ```bash
   npm install --save aws-xray-sdk
   ```
2. **Keep **`` but change the generated import to:
   ```js
   import AWSXRay from 'aws-xray-sdk-core';
   ```
   (and adjust the namespace export).

#### Work-arounds

- Disable tracing just for the warmer: `tracing: false`
- Manually add the full SDK to the warmer package:
  ```yaml
  package:
    patterns:
      - node_modules/aws-xray-sdk/**
  ```
- Pin the plugin to the last working line (<=7.x).

---

Thanks for maintaining this plugin! Let me know if any more diagnostics would help.
